# Generated by Django 2.1.1 on 2019-02-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='id_prueba',
            new_name='prueba',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='id_quiz',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='id_leccion',
            new_name='leccion',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='id_tema',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='id_pregunta',
            new_name='pregunta',
        ),
    ]
