# Generated by Django 2.1.1 on 2019-04-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_auto_20190403_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.Pregunta'),
        ),
    ]
