# Generated by Django 2.1.1 on 2019-04-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_auto_20190403_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
