# Generated by Django 2.1.1 on 2019-05-08 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=2)),
                ('mejor_nota', models.CharField(max_length=2)),
                ('intentos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.BooleanField(default=True)),
                ('podcast', models.BooleanField(default=True)),
                ('codigo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=1024, null=True)),
                ('presentaciond', models.CharField(max_length=1024, null=True)),
                ('podcast', models.CharField(max_length=1024, null=True)),
                ('codigo', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=320)),
                ('correcta', models.BooleanField()),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Leccion')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='tema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tema'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_T_FK', to='api.Tema'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_U_FK', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='prueba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Prueba'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Quiz'),
        ),
        migrations.AddField(
            model_name='link',
            name='tema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tema'),
        ),
        migrations.AddField(
            model_name='infotema',
            name='tema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tema'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_T_FK', to='api.Prueba'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_U_FK', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('usuario', 'tema')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('usuario', 'prueba')},
        ),
    ]
