# Generated by Django 2.1.1 on 2019-05-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190522_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Curso'),
        ),
    ]
