# Generated by Django 2.1.1 on 2019-03-23 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bucketlist_date_modified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
