# Generated by Django 2.1.1 on 2019-05-23 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_progreso_curso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('usuario', 'curso')},
        ),
    ]
