# Generated by Django 2.1.1 on 2019-05-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190523_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='repocodigo',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
