# Generated by Django 2.1.1 on 2019-02-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('contenido', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecciones.Leccion')),
            ],
        ),
        migrations.AddField(
            model_name='infotema',
            name='id_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecciones.Tema'),
        ),
    ]
