# Generated by Django 2.1.1 on 2019-02-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotema',
            old_name='id_tema',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='id_leccion',
            new_name='leccion',
        ),
    ]
