# Generated by Django 2.1.1 on 2019-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0003_auto_20190322_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=1024)),
                ('podcast', models.CharField(max_length=1024)),
                ('codigo', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='infotema',
            name='codigo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infotema',
            name='podcast',
            field=models.BooleanField(default=True),
        ),
    ]
