# Generated by Django 2.1.1 on 2019-04-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0004_auto_20190324_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotema',
            old_name='tema',
            new_name='tema1',
        ),
        migrations.AddField(
            model_name='link',
            name='tema2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecciones.Tema'),
        ),
    ]
