# Generated by Django 2.1.1 on 2019-04-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0005_auto_20190403_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotema',
            old_name='tema1',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='tema2',
            new_name='tema',
        ),
    ]
