# Generated by Django 2.1.1 on 2019-04-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0006_auto_20190403_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecciones.Tema'),
        ),
    ]
