# Generated by Django 2.1.1 on 2019-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0009_auto_20190403_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='presentaciond',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
