# Generated by Django 2.1.1 on 2019-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0010_link_presentaciond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='codigo',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='podcast',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='presentacion',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
