# Generated by Django 2.1.1 on 2019-04-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0011_auto_20190407_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecciones.Tema', unique=True),
        ),
    ]
