# Generated by Django 2.1.1 on 2019-04-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0013_auto_20190429_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotema',
            name='tema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecciones.Tema'),
        ),
        migrations.AlterField(
            model_name='link',
            name='tema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecciones.Tema'),
        ),
    ]
