# Generated by Django 2.1.1 on 2019-02-24 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=2)),
                ('mejor_nota', models.CharField(max_length=2)),
                ('intentos', models.IntegerField()),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.Prueba')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecciones.Tema')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('id_usuario', 'id_tema')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('id_usuario', 'id_prueba')},
        ),
    ]
