# Generated by Django 2.1.1 on 2019-02-24 03:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20190223_2306'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecciones', '0002_auto_20190223_2306'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='id_prueba',
            new_name='prueba',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='progreso',
            old_name='id_tema',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='progreso',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('usuario', 'prueba')},
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('usuario', 'tema')},
        ),
    ]
